"""add vocab_words

Revision ID: 354365d4ca9a
Revises: 88e950d72651
Create Date: 2026-07-26 20:26:53.997530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '354365d4ca9a'
down_revision: Union[str, Sequence[str], None] = '88e950d72651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocab_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('example_sentence', sa.Text(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('times_suggested', sa.Integer(), nullable=False),
    sa.Column('mastered', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word', name='uq_vocab_words_user_id_word')
    )
    op.create_index(op.f('ix_vocab_words_user_id'), 'vocab_words', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vocab_words_user_id'), table_name='vocab_words')
    op.drop_table('vocab_words')
    # ### end Alembic commands ###
